export const BOOK_LIST_FETCH_THUNK_TYPE = 'BOOK_LIST_FETCH_THUNK_TYPE';
export const BOOK_LIST_CREATE_THUNK_TYPE = 'BOOK_LIST_CREATE_THUNK_TYPE';
export const BOOK_LIST_UPDATE_FETCH_DATA_THUNK_TYPE =
  'BOOK_LIST_UPDATE_FETCH_DATA_THUNK_TYPE';
export const BOOK_LIST_UPDATE_THUNK_TYPE = 'BOOK_LIST_UPDATE_THUNK_TYPE';
export const BOOK_LIST_DELETE_THUNK_TYPE = 'BOOK_LIST_DELETE_THUNK_TYPE';
